kind: Deployment
apiVersion: apps/v1
metadata:
  name: example-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-react-app
  template:
    metadata:
      labels:
        app: example-react-app
    spec:
      containers:
        - name: example-react-app
          image: example-react-app
          imagePullPolicy: Never
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: example-react-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32000
  selector:
    app: example-react-app
